### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by karneaud** [jtpio/jammer#1]
Came across this framework and this is just what I am looking for.....is this still actively maintained?

**Comment by jtpio** [comment]
Unfortunately not actively, I have been going to fewer game jams, reducing the number of opportunities to use this framework.

But PRs and help are very welcome!

**Comment by karneaud** [comment]
@jtpio I'm mos def interested in contributing where I can do this. I have been actively looking at something along this lines since I saw http://www.airconsole.com. Maybe it is worth exploring yourself as the concept is similar in principle. Let me know your thoughts and roadmap if any

**Comment by jtpio** [comment]
Thank you for your interest and for sharing this tool!

There is no clear guidelines at the moment. As mentioned in the [Motivation section](https://github.com/jtpio/jammer/blob/master/README.md#motivation) in the README, the idea was to have something relatively simple and minimal for game jams.

So maybe this framework still has a role to play for small use cases (game jams or hobby projects for example), while the other commercial alternatives focus on more professional creations.

**Comment by karneaud** [comment]
Well thanks for this. I would try to develop and contribute where and when I can. Do hope you keep in the loop.

Thanks again
